[build]
  builder = "DOCKERFILE"

[build.env]
  NIXPACKS_NODE_VERSION = "20"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3
